config/routes.rb
ProjectHelp::Application.routes.draw do
  
  resources :thanks
  
  resources :password_resets
  
  post "topics/search"        => 'topics#search'
  get "topics/:id(.:format)"  => 'topics#show'
  
  get "network/"              => 'home#dashboard'

  resources :messages, only: [:create]
  resources :conversations, only: [:create, :update]
  get "inbox/:id(.:format)"   => 'conversations#show'
  get "inbox/"                => 'conversations#index'
  
  get "groups/:id(.:format)"  => 'groups#show'
  get "welcome/index"
  get "welcome/introduction"  => 'welcome#introduction'

  get '/users/:id/new2' =>  'users#new2'
  get '/users/admin' => 'users#admin_panel'

  resources :users 

  resources :posts, only: [:create, :update, :destroy, :show]
  resources :comments, only: [:create, :update, :destroy]

  post "sessions/create" => 'sessions#create'
  get "sessions/destroy"

  root 'welcome#index'

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :helpoffers, class_name: "Helpoffer", foreign_key: "user_id", dependent: :destroy
	has_many :topics, through: :helpoffers
	has_many :groupusers, dependent: :destroy
	has_many :groups, through: :groupusers
	has_many :posts, as: :postable, dependent: :destroy
	has_many :writeposts, class_name: "Post", foreign_key: "user_id", dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :user1s, class_name: "Conversation", foreign_key: "user1_id", dependent: :destroy
	has_many :user2s, class_name: "Conversation", foreign_key: "user2_id", dependent: :destroy
	has_many :senders, class_name: "Message", foreign_key: "sender_id", dependent: :destroy
	has_many :receivers, class_name: "Message", foreign_key: "receiver_id", dependent: :destroy
	has_many :notifications, class_name: "Notification", foreign_key: "user_id", dependent: :destroy
	has_many :profilenotes, as: :notifiable, class_name: "Notification", foreign_key: "notifiable_id", dependent: :destroy
	has_many :thanks, as: :thanked, class_name: "Thank", foreign_key: "thanked_id", dependent: :destroy
	has_many :thankers, class_name: "Thank", foreign_key: "thanker_id", dependent: :destroy
	has_many :thanked_users, class_name: "Thank", foreign_key: "thanked_uid", dependent: :destroy

	mount_uploader :image, ImageUploader

	accepts_nested_attributes_for :helpoffers, reject_if: proc {|attributes| attributes['title'].blank?},
		:allow_destroy 			=> true
		

	validates 	:email,	:presence				=> true,
				:email_format 					=> {message: "Invalid email address"},
				:uniqueness						=> {case_sensitive:false, message: "This email already exists"}
	validates	:first_name, :presence			=> true
	validates	:last_name, :presence			=> true
	validates	:phone_number, :numericality	=> true,
				:length							=> {is: 10},
				:unless 						=> lambda{ |user| user.phone_number.blank? }
	validates	:password, :presence			=> true,
				:length							=> {in: 6..40},
				:on								=> :create
	validates 	:password, 
				:confirmation 					=> true, 
				:length 						=> { :within => 6..40 }, 
				:on 							=> :update, 
				:unless 						=> lambda{ |user| user.password.blank? }

	before_save{ self.email.downcase! }
	has_secure_password

	# Generates a secure token and saves it in a given column for this user
	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

	# Generates data for the password_reset fields, then sends the password reset email to the user
	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent = Time.zone.now
		self.save!

		UserMailer.password_reset(self).deliver
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user?, only: [:edit, :update, :destroy, :new2]
  before_action :deny_access, only: [:admin_panel, :new2, :destroy, :show, :index, :edit, :update]

  def new
    if signed_in?
      redirect_to '/users'
    end

    @user = User.new
  end

  #Create a new user. This will only include basic information - it does not include Description or Help Offers
  def create

    group_id = Group.check_code(params['access_code'])

    if(group_id == false)
      redirect_to '/users/new', notice: 'Invalid Group Code'
    else

      if User.all.count == 0
        params['user']['admin'] = 1
      else
        params['user']['admin'] = 0
      end
      
      @user = User.new(user_params)

      respond_to do |format|

        #If the new user is saved without error, automatically create an entry in Groupuser to add this user to Group 1.
        #Then sign in the user
        if @user.save
          UserMailer.welcome_email(@user).deliver
          @group_user = Groupuser.new(user_id: @user.id, group_id: group_id, groupowner:0, groupadmin:0).save
          sign_in(@user)
          format.html { redirect_to '/welcome/introduction' } #@user, notice: 'User was successfully created.' }
          format.json { render action: 'show', status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end  
  end

  #Controller for admin page. Page that is only viewable to admins. They can see all users, edit users and destroy users
  def admin_panel
    if current_user.admin == 1
      @users = User.all
    else
      redirect_to "/users"
    end
  end

  #Part 2 of new member registration. This page will include a form to fill out the user's Description and add
  #Help Offers
  def new2
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_admin_url }
      format.json { head :no_content }
    end
  end

  def show
    @topics = @user.helpoffers
    @posts = @user.posts.includes({comments: [{thanks: :thanker}, :user]}, {thanks: :thanker}, :user).order("created_at DESC").all
    
    @newpost = session[:post] || @user.posts.new
    session.delete(:post)

    # Remove existing notifications on the current user's profile is the current user is viewing
    # their own profile
    if(@user.id == current_user.id)
      current_user.profilenotes.destroy_all
    end

    # Check if the user you're viewing is in any of the same groups as the viewer
    current_groups = current_user.groups.all.to_a
    viewed_groups = @user.groups.all.to_a

    if (current_groups & viewed_groups).empty?
      @same_group = false
    else
      @same_group = true
    end
    
    # for i in 0...groups.length
    #   if Groupuser.group_user_exist?(groups[i].id, @user.id)
    #     @same_group = true
    #     break
    #   end
    # end

    # Get the existing conversation between the viewer and the viewee, or create a new conversation
    # otherwise
    @conversation = Conversation.getConvo(current_user.id, @user.id)

    if @conversation.nil?
      @conversation = Conversation.new
    end

    @conversation.messages.build
    
    
  end

  def index
    deny_access
    
    # Grab all of the users that are in any of the same groups as the current_user

    # First grab all of the users
    all_users = User.all.to_a.sort_by { |obj| obj.first_name }

    @users = []

    # Go through each user and check if it is any of the same groups as the current user
    all_users.each do |user|
      if (user.groups.to_a & current_user.groups.to_a).length>0
        @users.push(user)
      end
    end

    # Store all of the help topics of these people have listed - all of the topics
    # that are available to this user
    @helptopics = []

    @users.each do |user|
      user.helpoffers.to_a.each do |topic|
        @helptopics.push(topic)
      end
    end

    @helptopics = @helptopics.sort_by { |obj| obj.title}
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    params[:user].delete(:password) if params[:user][:password].blank?

    # If helpoffers are being created, check if the topic title already exists
    # and if it doesn't, create the topic
    helpoffers = params['user']['helpoffers_attributes']
    if !helpoffers.blank?
      # if helpoffers.length == 1
      #   helpoffer = helpoffers[0]

      #   title = helpoffer['title']
      #   topic = Topic.check_topic(title)

      #   if !topic
      #     new_topic = Topic.new(name:self.title)
      #     new_topic.save
      #   end        
      # elsif
        helpoffers.each do |key, helpoffer|
          title = helpoffer['title']

          topic = Topic.check_topic(title)

          if !topic
            new_topic = Topic.new(name:title)
            new_topic.save
          end
        end
      # end
    end

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to "/users/"+params[:id].to_s } #@user, notice: 'User was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @user }
        format.json { render json: {:current=>true} }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :password, :password_confirmation, :description, :admin, :image, :remote_image_url, :access_code, :current, helpoffers_attributes: [:user_id, :id, :title, :description, '_destroy'])
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_helpoffer_fields.html.erb
<div class="form-group help-topics">
	<%= f.label :title, "New Topic" %>
	<%= f.text_field :title, class: "form-control", placeholder: "Topic e.g. Resume writing, Startups, or Skiing" %>
	<%= f.text_area :description, class: "form-control", placeholder: "Description e.g. I've worked at 3 different startups across different growth stages. Happy to discuss what it was like working at a startup and what they're looking for in candidates." %>
	<%= f.hidden_field :_destroy %>
  	<%= link_to "Remove topic", '#', class: "remove_fields", value: "Remove topic" %>
</div>

app/views/users/_helpoffer_form.html.erb
<div class="form-group help-topics">
	<%#= f.label :title, "New Topic" %>
	<%= f.text_field :title, class: "form-control", id: "add-topic-title-input",placeholder: "Topic e.g. Data analytics" %>
	<%= f.text_area :description, class: "form-control", id: "add-topic-description-input", placeholder: "Description e.g. I've worked as a data scientist at Google and Microsoft. I have experience with data analysis as well as infrastructure." %>
	<a href="" class="add-topic-submit-add">Submit and add another topic</a><br>
	<button class="add-topic-cancel btn btn-default">Cancel</button> 
	<button class="add-topic-submit btn btn-primary">Submit</button>
	<!-- <button class="add-topic-submit-add btn btn-success">Add another</button>  -->
</div>

app/views/users/admin_panel.html.erb
<h1>Listing users</h1>
<p><%=current_user.first_name+ " is signed in!"%></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name + " " +user.last_name%></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>
<%= link_to 'Sign Out', "/sessions/destroy" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45530906-1', 'projecthelp.co');
  ga('send', 'pageview');

</script>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div id="edit-container">
  <div class="col-sm-9 form-container">
    <%= form_for(setup_user(@user), :html => { :role => "form" }) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h2>
     
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
		
      <ul class="list-group">
      	<li class="list-group-item" id="edit-account-info">
      		<h3>Edit account info</h4>
	     	<div class="form-group">
		        <%= f.label :first_name%>
		        <%= f.text_field :first_name, class: "form-control"%>
	      	</div> 	

	      	<div class="form-group">
		        <%= f.label :last_name%>
		        <%= f.text_field :last_name, class: "form-control"%>
	      	</div> 	

	      	<div class="form-group">
		        <%= f.label :email%>
		        <%= f.text_field :email, class: "form-control"%>
	      	</div>

	      	<div class="form-group">
		        <%= f.label :phone_number%>
		        <%= f.text_field :phone_number, class: "form-control", placeholder: "12312312345 - numbers only please"%>
	      	</div> 	 	 	
	  	</li>
     
		<li class="list-group-item" id="edit-profile-info">
		  <h3>Edit profile info</h3>

		  <div class="form-group">
	        <div id="new2-choose-file">
	          <%= f.label :image, "Upload profile picture" %>
	          <%= f.file_field :image, class: "form-control" %>
	        </div>
	      
	        <%= f.text_field :remote_image_url, class: "form-control", placeholder: "Or enter an image URL" %>
	      </div>

	      <div class="form-group" id="current-role-field">
	        <%= f.label :current, "Current role" %>
	        <%= f.text_field :current, class: "form-control", placeholder: "Front-end dev at Google or Student at Coding Dojo" %>
	      </div>

	      <div class="form-group">
	        <%= f.label :description, "A little more about yourself" %>
	        <%= f.text_area :description, class: "form-control", placeholder: "I was a part of the November Coding Dojo class. Previously, I've worked in venture capital, in product management at a startup, and in finance. Call me!"%>
	      </div>
	  	</li>

	  	<li class="list-group-item" id="edit-help-topics">

	      <p id="edit-topic-heading" data-no-turbolink="true">
	      	<h3>Topics you would like to help people with</h3>
	      	<%= link_to_add_fields "Add More Topics", f, :helpoffers %>
	      </p>
	      
	      <% topic = 1 %>
	      <%= f.fields_for :helpoffers do |helpoffer_form| %>
	          
	          <div class="form-group help-topics" data-no-turbolink="true">
	            <%= helpoffer_form.label :title, "Topic #"+topic.to_s %>
	            <%= helpoffer_form.text_field :title, class: "form-control", placeholder:"Topic e.g. Startup recruiting" %>
	            <%= helpoffer_form.text_area :description, class: "form-control", placeholder:"Description e.g. I've worked at 3 different startups across different growth stages. Happy to discuss my experiences and give recruiting advice" %>
	            <%= helpoffer_form.hidden_field :_destroy %>
  				<%= link_to "Remove topic", '#', class: "remove_fields" %>
	          </div>

	          <% topic+= 1 %>
	      <% end %>
     
	      <div class="actions">
	      	<%= link_to "Cancel", :back, class: "btn btn-default" %>
	        <%= f.submit "Submit", class: "btn btn-primary submit-edit" %>
	      </div>
	  	</li>
	  </ul>
	<% end %>
  </div>
</div>

<%= javascript_tag do %>
  window.userID = '<%= j current_user.id.to_s %>';
<% end %>

<script>
	mixpanel.identify(userID);
	mixpanel.track("Edit Profile Visit");

	$(document).ready(function() {
		$(".submit-edit").click(function() {
			mixpanel.track("Edit Profile Submit");
		});
	});

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45530906-1', 'projecthelp.co');
  ga('send', 'pageview');

</script>

app/views/users/index.html.erb
<div class="row">
  <div id="index-help-topics" class="col-sm-8">
    <h3>Topics your network can help you with: </h3>
      
      <!-- Print out all of the topics people are willing to help with in your network and 
      have each link to that user's profile -->
      <% @helptopics.each_with_index do |topic, index| %>
        <% if index==@helptopics.size-1 %>
          <a href="/users/<%=topic.user_id%>" class="topic-link"><%=topic.title%></a>
        <% else %>  
          <a href="/users/<%=topic.user_id%>" class="topic-link"><%=topic.title%></a>,
        <% end %>
      <% end %>
  </div>
</div>

<div id="user-frame-container">
  <h3>People in your network:</h3>

  <% @users.each do |user| %>

    <% if user.id != current_user.id %>
    
      <!-- Determine if the user's description is too long to fit in the frame. If it is, take the first 190 characters of the description and set the description_cut variable to true -->
      <% if !user.description %>
        <% descr = "Description not added yet" %>
      <% elsif user.description.length>190 %>
        <% descr = user.description[0...190] + "..." %>
      <% else %>
        <% descr = user.description %>
      <% end %>

      <!-- Extract the titles of the HelpOffers for this user and place into a comma separated string to be printed out below -->
      <% helpoffers = [] %>
      <% if user.helpoffers.count == 0  %>
        <% helpoffers = "Topics not added yet" %>
      <% else %>
        <% user.helpoffers.each do |offer| %>
          <% helpoffers.push(offer.title) %>
        <% end %>
        <% helpoffers = helpoffers.join(", ") %>
      <% end %>

      <!-- Current role is either "Current role not added yet" or their current role-->
      <% if user.current.blank?  %>
        <% current_role = "Current role not added yet" %>
      <% else %>
        <% current_role = user.current %>
      <% end %>
      
      <div class="user-frame col-sm-3 well" >
          <div class="user-frame-img-holder">
            
            <!-- Check if user has an image. Use placekitten if not -->
            <% if user.image_url.nil? %>
              <img src = "http://placekitten.com/150/150">
            <% else %>
              <%= image_tag user.image_url.to_s %>
            <% end %>

          </div>

          <div class="user-frame-basic-info">
            <div class="user-frame-name">
              <p><h4><%= user.first_name + " " + user.last_name%></h4></p>
              <p class="user-frame-role"><%= current_role %></p>
            </div>
            
            <div class="helpoffers-div">
              <p class="user-frame-help-topics"><strong>Help topics:</strong>
              <%= helpoffers %></p>
            </div>

            <div class="description-div"> 
              <p><%= descr %></p>
            </div>      
            
            <div class="viewprofilebtn-div">
              <a href="/users/<%=user.id%>" class="btn btn-primary view-profile-button">View Full Profile</a>
            </div>

        </div>
      </div>
    <% end %>
  <% end %>
</div>



<%= javascript_tag do %>
  window.userID = '<%= j current_user.id.to_s %>';
<% end %>

<script>
  mixpanel.identify(userID);
  mixpanel.track("Network Visit Page");

  $(document).ready(function() {
    $('.topic-link').click(function () {
      mixpanel.track("Network - Topic Link Clicked");
    });

    $('.view-profile-button').click(function() {
      mixpanel.track("Network - View Full Profile Link Clicked");
    });
  });
  
  
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45530906-1', 'projecthelp.co');
  ga('send', 'pageview');

</script>

app/views/users/new.html.erb
<div id="container">

	<% if !flash[:notice].nil? %>
		<div class="col-sm-12 flash-notice">
			<%="#{flash[:notice]}"%>
		</div>
	<% end %>	

	<div class="col-sm-5 form-container">
		<h3> Sign In </h3>

		<%= simple_form_for(@user, url: '/sessions/create', :defaults => { :wrapper_html => {:class=>"form-group"}, :input_html => { :class => "form-control", :size=>'20' } }) do |f| %>
			<%= f.input :email, placeholder: "Email", label: false %>
			<%= f.input :password, placeholder: "Password", label: false%>
			<%= f.button :submit, input_html: {value: 'Sign in'},value:'Login', class: "btn btn-primary"%>
			     <span class="forgot-password">&#8901 <%= link_to "Forgot password?", new_password_reset_path %></span>
		<% end %>

	</div>
	
	<div class= "col-sm-5 registration-form-container">
		<h3> Registration </h3>
		
		<% if @user.errors.any? %>
			<%= render partial: "/shared/errors", locals: {:save_obj=>@user, :save_str=>"User"} %>
		<% end %>

		<%#= simple_form_for(@user, :defaults => { :wrapper_html => {:class=>"form-group"}, :input_html => { :class => "form-control" } }) do |f| %>
			<%#= f.input :first_name, label: "First Name:" %>
			<%#= f.input :last_name, label: "Last Name:" %>
			<%#= f.input :email, label: "Email:" %>
			<%#= f.input :password, label: "Password:" %>
			<%#= f.input :password_confirmation, label: "Confirm Password:" %>
			<%#= f.button :submit, input_html: {value: 'Create User'},value:'Register', class: "btn btn-primary"%>
		<%# end %>

		<%= form_for(@user, :html => { :role => "form", :id=>"register" }) do |f| %>
				<div class="form-group">
					<div class="form-inline">
						<div class="form-group col-sm-6" id="first-name-input">
							<label class="sr-only" for="user[first_name]">First Name</label>
							<%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
						</div>
						<div class="form-group col-sm-6" id="last-name-input">
							<label class="sr-only" for="user[last_name]">Last Name</label>
							<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
						</div>
					</div>
				</div>

				<div class="form-group">
					<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
				</div>

				<div class="form-group">
					<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
				</div>

				<div class="form-group">
					<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
				</div>

				<div class="form-group">
					<input class="form-control" type="text" name="access_code" placeholder="Group Code"></input>
				</div>

				<%= f.submit "Register", class: "btn btn-primary" %>
			<% end %>
	</div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45530906-1', 'projecthelp.co');
  ga('send', 'pageview');

</script>

app/views/users/new2.html.erb
<h3>Complete your profile and get started!</h3>

<div id="container">
  <div class="col-sm-7 form-container">
    <%= form_for(setup_user(@user), :html => { :role => "form" }) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h2>
     
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <div id="new2-choose-file">
          <%= f.label :image, "Upload profile picture" %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
      
        <%= f.text_field :remote_image_url, class: "form-control", placeholder: "Or enter an image URL" %>
      </div>
     
      <div class="form-group" id="phonenumber-field">
        <%= f.label :phone_number, "Phone number (notifications for new messages)" %>
        <%= f.text_field :phone_number, class: "form-control", placeholder: "12312312345 - numbers only please" %>
      </div>

      <div class="form-group" id="current-role-field">
        <%= f.label :current, "Current role" %>
        <%= f.text_field :current, class: "form-control", placeholder: "Front-end dev at Google or Student at Coding Dojo" %>
      </div>

      <div class="form-group" id="description-field">
        <%= f.label :description, "Briefly describe yourself: interests, hobbies, past experiences" %>
        <%= f.text_area :description, class: "form-control", placeholder: "I was a part of the November Coding Dojo class. Previously, I've worked in venture capital, in product management at a startup, and in finance. Call me!" %>
      </div>
     
      <div class="actions">
        <a href="/users/<%=current_user.id.to_s%>" class="btn btn-default" >Skip</a>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_tag do %>
  window.userID = '<%= j current_user.id.to_s %>';
<% end %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45530906-1', 'projecthelp.co');
  ga('send', 'pageview');

  mixpanel.alias(userID);
  mixpanel.track("New User Registered");

</script>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>